name: Run build
on: [push]
jobs:
  Build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: pip install numpy pytest cython opencv-python
      - run: pip install -v .
      - run: pytest tests
