name: Test and Publish package

on:
  push:
    branches: [ "feature/*" ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 build wheel auditwheel cython numpy pytest opencv-python
        pip install -v -e .
    - name: Lint with flake8
      run: |
        flake8 fast_bfmatcher --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 fast_bfmatcher --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest -s
    - name: Build package
      # https://github.com/pypa/auditwheel/issues/291
      run: |
        python -m build
        auditwheel repair --plat manylinux_2_27_x86_64 `ls -1 dist/*-linux*.whl`
        mv wheelhouse/* dist
        rm dist/*-linux_x86_64.whl
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}